spring:
  main:
    web-application-type: reactive
  application:
    name: truproxyapi
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost:27017/truproxy
#debug: true
proxy:
  endpoint: "http://localhost:1080/"

